# Generated by Django 4.2.5 on 2023-09-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surename", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=255)),
                ("password", models.CharField(max_length=20, null=True)),
            ],
            options={
                "db_table": "clients",
            },
        ),
    ]
