# Generated by Django 4.2.5 on 2023-09-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=70)),
                ("Theme", models.CharField(max_length=70)),
                ("questions", models.CharField(max_length=500)),
                ("quote", models.CharField(max_length=300, null=True)),
            ],
            options={
                "db_table": "quiz",
            },
        ),
    ]
